# Generated by Django 5.2.6 on 2025-09-17 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_customuser_age_alter_customuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Admin', 'admin'), ('Seller', 'seller'), ('Customer', 'customer'), ('Viewer', 'viewer')], default='Viewer'),
        ),
    ]
