# Generated by Django 5.2.6 on 2025-09-24 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='default/kim.jpg', null=True, upload_to='avatar'),
        ),
    ]
