# Generated by Django 5.2.6 on 2025-10-06 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ustudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_count', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
    ]
