# Generated by Django 5.2.6 on 2025-09-15 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olx', '0002_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
